# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/baiquan/Documents/log/Log_01

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/baiquan/Documents/log/Log_01

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/baiquan/Documents/log/Log_01/CMakeFiles /home/baiquan/Documents/log/Log_01/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/baiquan/Documents/log/Log_01/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server_Log

# Build rule for target.
server_Log: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server_Log
.PHONY : server_Log

# fast build rule for target.
server_Log/fast:
	$(MAKE) -f CMakeFiles/server_Log.dir/build.make CMakeFiles/server_Log.dir/build
.PHONY : server_Log/fast

#=============================================================================
# Target rules for targets named Testlog

# Build rule for target.
Testlog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Testlog
.PHONY : Testlog

# fast build rule for target.
Testlog/fast:
	$(MAKE) -f Test/CMakeFiles/Testlog.dir/build.make Test/CMakeFiles/Testlog.dir/build
.PHONY : Testlog/fast

AsyncLogging.o: AsyncLogging.cpp.o

.PHONY : AsyncLogging.o

# target to build an object file
AsyncLogging.cpp.o:
	$(MAKE) -f CMakeFiles/server_Log.dir/build.make CMakeFiles/server_Log.dir/AsyncLogging.cpp.o
.PHONY : AsyncLogging.cpp.o

AsyncLogging.i: AsyncLogging.cpp.i

.PHONY : AsyncLogging.i

# target to preprocess a source file
AsyncLogging.cpp.i:
	$(MAKE) -f CMakeFiles/server_Log.dir/build.make CMakeFiles/server_Log.dir/AsyncLogging.cpp.i
.PHONY : AsyncLogging.cpp.i

AsyncLogging.s: AsyncLogging.cpp.s

.PHONY : AsyncLogging.s

# target to generate assembly for a file
AsyncLogging.cpp.s:
	$(MAKE) -f CMakeFiles/server_Log.dir/build.make CMakeFiles/server_Log.dir/AsyncLogging.cpp.s
.PHONY : AsyncLogging.cpp.s

FIleUtile.o: FIleUtile.cpp.o

.PHONY : FIleUtile.o

# target to build an object file
FIleUtile.cpp.o:
	$(MAKE) -f CMakeFiles/server_Log.dir/build.make CMakeFiles/server_Log.dir/FIleUtile.cpp.o
.PHONY : FIleUtile.cpp.o

FIleUtile.i: FIleUtile.cpp.i

.PHONY : FIleUtile.i

# target to preprocess a source file
FIleUtile.cpp.i:
	$(MAKE) -f CMakeFiles/server_Log.dir/build.make CMakeFiles/server_Log.dir/FIleUtile.cpp.i
.PHONY : FIleUtile.cpp.i

FIleUtile.s: FIleUtile.cpp.s

.PHONY : FIleUtile.s

# target to generate assembly for a file
FIleUtile.cpp.s:
	$(MAKE) -f CMakeFiles/server_Log.dir/build.make CMakeFiles/server_Log.dir/FIleUtile.cpp.s
.PHONY : FIleUtile.cpp.s

LogFile.o: LogFile.cpp.o

.PHONY : LogFile.o

# target to build an object file
LogFile.cpp.o:
	$(MAKE) -f CMakeFiles/server_Log.dir/build.make CMakeFiles/server_Log.dir/LogFile.cpp.o
.PHONY : LogFile.cpp.o

LogFile.i: LogFile.cpp.i

.PHONY : LogFile.i

# target to preprocess a source file
LogFile.cpp.i:
	$(MAKE) -f CMakeFiles/server_Log.dir/build.make CMakeFiles/server_Log.dir/LogFile.cpp.i
.PHONY : LogFile.cpp.i

LogFile.s: LogFile.cpp.s

.PHONY : LogFile.s

# target to generate assembly for a file
LogFile.cpp.s:
	$(MAKE) -f CMakeFiles/server_Log.dir/build.make CMakeFiles/server_Log.dir/LogFile.cpp.s
.PHONY : LogFile.cpp.s

Logging.o: Logging.cpp.o

.PHONY : Logging.o

# target to build an object file
Logging.cpp.o:
	$(MAKE) -f CMakeFiles/server_Log.dir/build.make CMakeFiles/server_Log.dir/Logging.cpp.o
.PHONY : Logging.cpp.o

Logging.i: Logging.cpp.i

.PHONY : Logging.i

# target to preprocess a source file
Logging.cpp.i:
	$(MAKE) -f CMakeFiles/server_Log.dir/build.make CMakeFiles/server_Log.dir/Logging.cpp.i
.PHONY : Logging.cpp.i

Logging.s: Logging.cpp.s

.PHONY : Logging.s

# target to generate assembly for a file
Logging.cpp.s:
	$(MAKE) -f CMakeFiles/server_Log.dir/build.make CMakeFiles/server_Log.dir/Logging.cpp.s
.PHONY : Logging.cpp.s

Logging_BK.o: Logging_BK.cpp.o

.PHONY : Logging_BK.o

# target to build an object file
Logging_BK.cpp.o:
	$(MAKE) -f CMakeFiles/server_Log.dir/build.make CMakeFiles/server_Log.dir/Logging_BK.cpp.o
.PHONY : Logging_BK.cpp.o

Logging_BK.i: Logging_BK.cpp.i

.PHONY : Logging_BK.i

# target to preprocess a source file
Logging_BK.cpp.i:
	$(MAKE) -f CMakeFiles/server_Log.dir/build.make CMakeFiles/server_Log.dir/Logging_BK.cpp.i
.PHONY : Logging_BK.cpp.i

Logging_BK.s: Logging_BK.cpp.s

.PHONY : Logging_BK.s

# target to generate assembly for a file
Logging_BK.cpp.s:
	$(MAKE) -f CMakeFiles/server_Log.dir/build.make CMakeFiles/server_Log.dir/Logging_BK.cpp.s
.PHONY : Logging_BK.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... server_Log"
	@echo "... Testlog"
	@echo "... AsyncLogging.o"
	@echo "... AsyncLogging.i"
	@echo "... AsyncLogging.s"
	@echo "... FIleUtile.o"
	@echo "... FIleUtile.i"
	@echo "... FIleUtile.s"
	@echo "... LogFile.o"
	@echo "... LogFile.i"
	@echo "... LogFile.s"
	@echo "... Logging.o"
	@echo "... Logging.i"
	@echo "... Logging.s"
	@echo "... Logging_BK.o"
	@echo "... Logging_BK.i"
	@echo "... Logging_BK.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

